# Docker Compose file that brings up containers necessary for GFIPM HTTPD environment
# To run:  docker-compose -f gfipm.yaml up -d
# Prior to running, be sure to update the .env file (in this directory) with Github token and username
version: '3'

networks:
  gfipm_nw:
    driver: bridge
    ipam:
      driver: default
      config:
      -
       subnet: 172.16.0.0/16

services:

  gfipm-httpd-proxy:
    container_name: gfipm-httpd-proxy
    image: ojbc/gfipm-httpd-proxy
    networks:
      gfipm_nw:    
    build:
      context: ./gfipm-httpd-proxy
        # we need this volume since this SSL cert and key must be on the docker host file system
    ports: 
      - "443:443"
    volumes:
       - "${HOST_CERT_PATH:-/opt/gfipm-certs/}:/opt/gfipm-certs/"
 #
  ojb-web-util:
   container_name: ojb-web-util
   image: ojbc/ojb-web-util
   networks:
     gfipm_nw:

